# Generated by Django 5.1.6 on 2025-03-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_attributegroup_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.attribute'),
        ),
    ]
