# Generated by Django 5.1.6 on 2025-03-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productattribute_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
