# Generated by Django 5.1.7 on 2025-03-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productattribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('assigned', 'assigned'), ('under maintenance', 'under maintenance'), ('retired', 'retired'), ('lost', 'lost')], default='available', max_length=20),
        ),
    ]
