# Generated by Django 5.1.6 on 2025-02-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='group',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
