# Generated by Django 5.1.6 on 2025-02-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_attribute_group_delete_productattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
