# Generated by Django 5.1.6 on 2025-02-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_employee_delete_employee_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
