# Generated by Django 5.1.6 on 2025-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
