# Generated by Django 5.1.6 on 2025-02-16 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='IMEI phải có 15 hoặc 16 chữ số.', regex='^[0-9]{15}$')]),
        ),
    ]
