# Generated by Django 5.1.6 on 2025-02-17 18:17

import authentication.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_device_imei'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_phone_numbers', models.CharField(max_length=15, validators=[authentication.validators.validate_phone_number])),
                ('value', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('shipping', 'Đang giao'), ('completed', 'Đã giao'), ('canceled', 'Đã hủy')], default='pending', max_length=20)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
