# Generated by Django 5.1.6 on 2025-02-17 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_phone_numbers',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ.', regex='^0[0-9]{9,10}$')]),
        ),
    ]
