# Generated by Django 5.1.6 on 2025-02-28 08:23

import django.utils.timezone
import users.constants
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(default=users.constants.Role['GUEST'], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_password_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(error_messages={'unique': 'Số điện thoại này đã tồn tại.'}, max_length=15, unique=True, validators=[users.validators.validate_phone_number])),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'Địa chỉ email này đã tồn tại.'}, max_length=254, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verify_phone_number', models.BooleanField(default=False)),
                ('is_verify_email', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
