# Generated by Django 5.1.7 on 2025-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
