# Generated by Django 5.2 on 2025-04-13 13:19

import web.validators.user
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[web.validators.user.validate_phone_number])),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('points', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
