# Generated by Django 5.2 on 2025-04-13 17:48

import web.constants.device
import web.constants.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_brand_alter_user_role_product_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Có sẵn', 'Có sẵn'), ('Đã bán', 'Đã bán')], default=web.constants.device.DeviceStatus['AVAILABLE'], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Android', 'Android'), ('iPhone (IOS)', 'iPhone (IOS)'), ('Điện thoại phổ thông', 'Điện thoại phổ thông')], max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default=web.constants.user.Gender['MALE'], max_length=16),
        ),
    ]
