# Generated by Django 5.2 on 2025-04-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_device_status_alter_product_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brands',
        ),
    ]
