# Generated by Django 5.2 on 2025-04-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
