# Generated by Django 5.2 on 2025-04-16 10:02

import django.db.models.deletion
import django.utils.timezone
import web.validators.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_delivered', models.DateTimeField(blank=True, null=True)),
                ('time_shipping', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.PositiveBigIntegerField()),
                ('total_amount_transfer', models.PositiveBigIntegerField()),
                ('total_amount_cash', models.PositiveBigIntegerField()),
                ('buyer_phone_number', models.CharField(max_length=15, validators=[web.validators.user.validate_phone_number])),
                ('buyer_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('point_used', models.PositiveBigIntegerField()),
                ('point', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('total_amount', models.PositiveBigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
            ],
            options={
                'db_table': 'order_products',
            },
        ),
    ]
