# Generated by Django 5.1.6 on 2025-03-12 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import orders.constants
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0006_alter_productattribute_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "buyer_phone_number",
                    models.CharField(max_length=15, validators=[users.validators.validate_phone_number]),
                ),
                ("price", models.PositiveBigIntegerField()),
                ("payment_method", models.CharField(max_length=15)),
                ("status", models.CharField(default=orders.constants.OrderStatus["PENDDING"], max_length=15)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.device")),
                ("saler", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "orders",
            },
        ),
    ]
