# Generated by Django 5.1.7 on 2025-03-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_paid_order_is_receive_in_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendding', 'pendding'), ('verified', 'verified'), ('shipping', 'shipping'), ('canceled', 'canceled'), ('success', 'success')], default='pendding', max_length=20),
        ),
    ]
