# Generated by Django 5.1.7 on 2025-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('viet-qr', 'viet-qr')], default='cash', max_length=25),
        ),
    ]
