# Generated by Django 5.1.7 on 2025-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_saler'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
