# Generated by Django 5.1.7 on 2025-03-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='final_price',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='order',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
