# Generated by Django 5.1.7 on 2025-03-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_final_price_order_product_price_order_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='points',
            new_name='buyer_points',
        ),
    ]
