# Generated by Django 5.1.4 on 2025-02-04 06:03

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. Phone number start with +xx or 0.', max_length=15, unique=True, validators=[authentication.validators.validate_phone_number]),
        ),
    ]
