# Generated by Django 5.1.4 on 2025-02-05 13:03

import authentication.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=authentication.constants.Role['GUEST'], max_length=10),
        ),
    ]
