# Generated by Django 5.1.6 on 2025-02-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Địa chỉ email này đã tồn tại.'}, max_length=254, null=True, unique=True),
        ),
    ]
